device: "auto" 
output_dir: "runs/predict"
save_vis: false

default_material_id: 0 # e.g., 0 for 'graphene'

models:
  detector:
    weights: "weights/yolo_flake.pt" 
    conf_thresh: 0.25
    iou_thresh: 0.45
  
  classifier:
    weights: "weights/flake_classifier.pth"
    num_materials: 4
    material_dim: 64
    freeze_cnn: false